### PR TITLE
fix(stats): Exclude passive checks from latency

### LINKED ISSUE #19: Latency wrongly computed
Hi,

I think latency is wrongly computed.

Here's an example :

mac

```
MariaDB [centreon_storage]> select max(latency) from services;
+--------------+
| max(latency) |
+--------------+
|    10.334141 |
+--------------+
```

But these 10.33 seconds (!) are from a passive check.
Let's now omit passive checks (not sure about the best way to exclude them, but this works as per my use case) :

```
MariaDB [centreon_storage]> select max(latency) from services where active_checks=1;
+--------------+
| max(latency) |
+--------------+
|        1.181 |
+--------------+
```

And this value is also returned by Centreon GUI in Administration / Engine statistics :

mac2

Could we then exclude passive checks from latency formula ?

Thank you 👍

Edit : issue still present in 19.10.0-beta.2.

### PR DESCRIPTION
**Pull request by CPbN**
Hi,

This closes #19, excluding passive checks from latency computation.

Thank you :+1: 

Edit : issue still present in 19.10.0-beta.2.

### CODE REVIEW

**Comment by CPbN** [comment]
Some news perhaps regarding this tiny PR ? @lpinsivy ?
Many thanks :+1:

**Comment by CPbN** [comment]
Hi @ganoze, while in widgets, perhaps we could merge this ?
Many thanks :+1:

**Comment by ganoze** [comment]
@CPbN Unfortunately my capabilities regarding widgets are limited to version bumps :-(

Maybe @lpinsivy would agree to quickly schedule a review of your PR ?

**Comment by CPbN** [comment]
No problem @ganoze, it was just while you were here, so no hurry :)
Thank you again :)

**Comment by CPbN** [comment]
Just rebased with master.
Thx 👍

**Comment by CPbN** [comment]
Still facing this in 19.10.0-beta.2, let's then merge this tiny PR please ?
Thank you very much :+1:

**Pull request merged**
